Settings:
  #Начальные жизни, очки, здоровье
  default-lives: 9
  default-points: 0
  default-health: 2

  # Изначальная цена за одну жизнь
  lives-cost: 350
  # На сколько будет увеличиваться цена при покупке жизней
  lives-cost-upgrade: 150

  # Можно указывать в формате чере ":" чтобы игрок получал
  # рандомное значение (10:15 будет выдавать от 10 до 15 очков)

  # Сколько очков получит игрок при ачивке
  achievement-get: "10:15"
  # Сколько очков игрок потеряет при использовании тотема бессмертия
  totem-use: "40:55"