name: NineHealth
version: ${project.version}
main: com.rainchat.ninehealth.NineHealth
api-version: 1.16
authors: [ rainchat ]

commands:
  ninehealth:
    aliases:
      - nh
      - healthrain
    description: ninehealth